variables:
  LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -p pdebug --userns"
  QUAY_HOST: "quay.apps.czapps.llnl.gov"
  QUAY_ORG: "/exaworks/sdk-"
  QUAY_LATEST: "latest"

stages:
  - build
  - test

Container Build:
  stage: build
  parallel:
    matrix:
      - BASE: ["centos7", "rockylinux8", "ubuntu"]
        PACKAGE_MANAGER: ["pip", "conda"]
        MPI: ["openmpi", "mpich"]


  before_script:
    - whoami
  tags:
    - quartz
    - batch
  needs: []
  script:
    - >
        for i in $(seq 1 $CI_NODE_TOTAL); do
        podman login -u $BOT_NAME -p $BOT_TOKEN $QUAY_HOST && s=0 && break ||
        s=$? && sleep 5; done; (exit $s)

    - export tag=${QUAY_HOST}${QUAY_ORG}${BASE}-${PACKAGE_MANAGER}-${MPI}:$QUAY_LATEST
    - export lcbase=${QUAY_HOST}/lcweg/lc-${BASE}
    - echo "Base Image is $lcbase"
    - >
        for i in $(seq 1 $CI_NODE_TOTAL); do
        podman pull $lcbase && s=0 && break ||
        s=$? && sleep 5; done; (exit $s)

    - >
        podman build -t base -f docker/base/${BASE}*/Dockerfile
        --build-arg BASE_IMAGE=${lcbase} --build-arg MPI=${MPI}
        --build-arg PACKAGE_MANAGER=${PACKAGE_MANAGER}
        --format docker docker/base/


    - podman build --format docker -t flux --build-arg BASE_IMAGE=base docker/flux
    - podman build --format docker -t parsl --build-arg BASE_IMAGE=flux docker/parsl
    - podman build --format docker -t rct --build-arg BASE_IMAGE=parsl docker/rct
    - podman build --format docker -t swift-t --build-arg BASE_IMAGE=rct docker/swift-t
    - podman build --format docker -t $tag --build-arg BASE_IMAGE=swift-t docker/integration

    - >
        for i in $(seq 1 $CI_NODE_TOTAL); do
        podman push ${tag} && s=0 && break ||
        s=$? && sleep 5; done; (exit $s)

    - podman logout $QUAY_HOST


Container Test:
  stage: test
  parallel:
    matrix:
      - BASE: ["centos7", "rockylinux8", "ubuntu"]
        PACKAGE_MANAGER: ["pip", "conda"]
        MPI: ["openmpi", "mpich"]

  before_script:
    - whoami
  tags:
    - quartz
    - batch
  needs: [Container Build]
  script:
    - export tag=${QUAY_HOST}${QUAY_ORG}${BASE}-${PACKAGE_MANAGER}-${MPI}:$QUAY_LATEST
    - >
        for i in $(seq 1 $CI_NODE_TOTAL); do
        podman login -u $BOT_NAME -p $BOT_TOKEN $QUAY_HOST && s=0 && break ||
        s=$? && sleep 15; done; (exit $s)

    - echo "Image Tag = ${tag}"
    - >
        for i in $(seq 1 $CI_NODE_TOTAL); do
        podman pull $tag && s=0 && break ||
        s=$? && sleep 15; done; (exit $s)

    - >
        for CORE in flux parsl rp swift-t flux-parsl; do
        podman run -it $tag bash --login -c "/tests/$CORE/test.sh";
        done;

    - podman logout $QUAY_HOST

Spack Build:
  stage: build
  tags:
    - quartz
    - shell
  needs: []
  before_script:
    - rm -rf $SPACK_WORK_DIR/spack/
  script:
    - cd $SPACK_WORK_DIR/
    - git clone -c feature.manyFiles=true https://github.com/spack/spack.git
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - spack install exaworks
    - spack install py-pytest

Spack Test:
  stage: test
  parallel:
      matrix:
        - TEST : ["rp", "swift-t", "parsl", "flux", "rp-flux", "parsl-flux"]
  before_script:
    - whoami
  tags:
    - quartz
    - batch
  needs: [Spack Build]
  script:
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - spack load exaworks py-pytest
    - export RADICAL_PILOT_DBURL=${MONGODB_CONNECTION_STRING}?tlsAllowInvalidCertificates=true
    - bash ci/tests/${TEST}/test.sh
  after_script:
    - whoami
