variables:
  LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -p pdebug --userns"


stages:
  - build
  - test

bulid_image:
  stage: build
  before_script:
    - whoami
    - ls
  tags:
    - quartz
    - batch
  script:
    - singularity build -t exaworks/sdk-base -f docker/base/centos7/Dockerfile docker/base/
    - singularity build -t flux --build-arg BASE_IMAGE=exaworks/sdk-base docker/flux

run_test:
  stage: test
  before_script:
    - whoami
  tags:
    - quartz
    - batch
  script:
    - singularity run flux
    - ret_flux=$?
    - echo $ret_flux
