pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=master
      - status-success="Run test suite (centos7, pip)"
      - status-success="Run test suite (centos8, pip)"
      - status-success="Run test suite (centos8, conda)"
      - status-success="Run test suite (ubuntu2004, pip)"
      - status-success="Run test suite (ubuntu2004, conda)"
      - status-success="validate commits"
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: smart+fasttrack
