version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
    - openjdk-11-jre
    - wget
    - tar
    - ant
    - mpich
    - swig
    - tcl-dev
    - zsh
  jobs:
    post_install:
      - wget http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-debs-1.3.tar.gz
      - tar xfz swift-t-debs-1.3.tar.gz
      - dpkg -i swift-t-debs/exmcutils-dev_0.5.4_amd64.deb
      - dpkg -i swift-t-debs/adlbx-dev_0.8.1_amd64.deb
      - dpkg -i swift-t-debs/turbine_1.1.0_amd64.deb
      - dpkg -i swift-t-debs/stc_0.7.4_amd64.deb

formats: all

python:
  install:
    - requirements: docs/source/requirements.txt
  system_packages: true

