version: 2
formats: all

build:
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
    - openjdk=11

python:
  version: 3.7
  install:
    - requirements: docs/source/requirements.txt
  system_packages: true