version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
    - openjdk-11-jdk
    # - gcc
    # - g++
    # - autoconf
    # - wget
    # - tar
    - ant
    - mpich
    - swig
    # - tcl-dev
    - zsh
  jobs:
    post_install:
      - wget http://swift-lang.github.io/swift-t-downloads/1.6/swift-t-1.6.0.tar.gz
      - tar xfz swift-t-1.6.0.tar.gz
      - swift-t-1.6.0/dev/build/init-settings.sh
      - swift-t-1.6.0/dev/build/build-swift-t.sh

formats: all

python:
  install:
    - requirements: docs/source/requirements.txt
  system_packages: true

