version: 2
formats: all

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
    - openjdk-11-jre
    - wget
    - tar
  jobs:
    post_install:
      - wget http://swift-lang.github.io/swift-t-downloads/1.3/swift-t-debs-1.3.tar.gz
      - tar xfz swift-t-debs-1.3.tar.gz
      - ./swift-t-debs/install-debs.sh

python:
  version: 3.7
  install:
    - requirements: docs/source/requirements.txt
  system_packages: true

