channels:
  - anaconda
  - conda-forge
  - lightsource2-tag
  - defaults
dependencies:
  - python=3.7
  - swift-t
  - parsl
  - radical.pilot
  - flux-core
  - flux-sched
  - pip
  - pip:
    - pytest==7.2.2
    - pytest-tap==3.3
    - requests==2.28.1
