variables:
  PIP_WORK_DIR: ${SDK_WORK_DIR}/pip
  PIP_REQUIREMENTS: .gitlab/pip-requirements.txt
  RADICAL_PILOT_DBURL: ${MONGODB_CONNECTION_STRING}?tlsAllowInvalidCertificates=true


stages:
  - setup
  - build
  - test
  - cleanup


### MACHINES
.on_quartz:
  variables:
    HOST: "quartz"
    VENV_ENV_NAME: "quartz-env"

.on_ruby:
  variables:
    HOST: "ruby"
    VENV_ENV_NAME: "ruby-env"

.on_lassen:
  variables:
    HOST: "lassen"
    VENV_ENV_NAME: "lassen-env"


### SCRIPTS
.final_steps:
  script: &finalize
    - chgrp -fR exaworks ${PIP_WORK_DIR} || true
    - chmod -fR 02770 ${PIP_WORK_DIR}    || true

.job_tags:
  tags:
    - $HOST
    - $RUNNER_TYPE

.pip_env_setup:
  stage: setup
  script:
    - mkdir -p ${PIP_WORK_DIR}
    - test -d ${PIP_WORK_DIR}/${VENV_ENV_NAME} && exit 0
    - python3 -m venv ${PIP_WORK_DIR}/${VENV_ENV_NAME}
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install -U pip setuptools wheel
    - pip cache purge
    - *finalize

.pip_build:
  stage: build
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install --no-cache-dir -r ${PIP_REQUIREMENTS}
    - *finalize

.pip_test:
  stage: test
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - export run_id=${CI_PIPELINE_ID}
    - export branch=${CI_COMMIT_BRANCH}
    - export url=${TESTING_HOST}
    - export test="Pip"
    - export location="llnl-$HOST"
    - export contact="arambula2@llnl.gov"
    - export imnumber="LLNL-MI-834241"
    - python3 ci/tests/test.py -s
    - for TEST in flux parsl rp swift-t parsl-flux rp-flux maestro; do
        python3 ci/tests/test.py -n $TEST -c "bash ci/tests/${TEST}/test.sh";
      done
    - python3 ci/tests/test.py -e
    - deactivate

### JOBS

# QUARTZ
pip_env_setup_quartz:
  variables:
    RUNNER_TYPE: "shell"
  extends: [ .on_quartz, .job_tags, .pip_env_setup ]

pip_build_quartz:
  variables:
    RUNNER_TYPE: "shell"
  needs: [ pip_env_setup_quartz ]
  extends: [ .on_quartz, .job_tags, .pip_build ]

pip_test_quartz:
  variables:
    RUNNER_TYPE: "batch"
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -t 30"
  needs: [ pip_build_quartz ]
  extends: [ .on_quartz, .job_tags, .pip_test ]


# RUBY
pip_env_setup_ruby:
  variables:
    RUNNER_TYPE: "shell"
  extends: [ .on_ruby, .job_tags, .pip_env_setup ]

pip_build_ruby:
  variables:
    RUNNER_TYPE: "shell"
  needs: [ pip_env_setup_ruby ]
  extends: [ .on_ruby, .job_tags, .pip_build ]

pip_test_ruby:
  variables:
    RUNNER_TYPE: "batch"
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -t 30"
  needs: [ pip_build_ruby ]
  extends: [ .on_ruby, .job_tags, .pip_test ]


# LASSEN
pip_env_setup_lassen:
  variables:
    RUNNER_TYPE: "shell"
  extends: [ .on_lassen, .job_tags, .pip_env_setup ]

pip_build_lassen:
  variables:
    RUNNER_TYPE: "shell"
  needs: [ pip_env_setup_lassen ]
  extends: [ .on_lassen, .job_tags, .pip_build ]
  before_script:
    - .gitlab/llnl-lassen-openssl-parsl.sh ${PIP_WORK_DIR}/${VENV_ENV_NAME}

pip_test_lassen:
  variables:
    RUNNER_TYPE: "batch"
    LLNL_LSF_SCHEDULER_PARAMETERS: "-nnodes 1 -W 30"
    LSB_JOB_STARTER: "ENVIRONMENT=BATCH /usr/tcetmp/bin/bsub_job_starter %USRCMD"
    EVIRONMENT: "BATCH"
  needs: [ pip_build_lassen ]
  extends: [ .on_lassen, .job_tags, .pip_test ]


# ALWAYS
pip_cleanup:
  stage: cleanup
  when: always
  variables:
    RUNNER_TYPE: "shell"
  extends: [ .on_quartz, .job_tags ]
  script:
   - *finalize

