stages:
  - update
  - build rhel7-broadwell
  - build rhel7-ppc64le
  - build rhel7-cascadelake
  - test

Spack Update:
  stage: update
  tags:
    - quartz
    - shell
  script:
    - cd $SPACK_WORK_DIR/spack/
    - git checkout HEAD^ .
    - git pull --ff
    - chmod -fR 02770 . || true

Spack Build rhel7-broadwell:
  stage: build rhel7-broadwell
  variables:
    HOST : "quartz"
    SPACK_ENV_NAME : "rhel7-broadwell"
    COMPILER : "gcc@8.1.0"
  tags:
    - $HOST
    - shell
  script: &build_script
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - spack env activate $SPACK_ENV_NAME
    - spack uninstall -y exaworks%$COMPILER  || true
    - spack uninstall -y py-pytest%$COMPILER || true
    - spack install --fresh exaworks%$COMPILER py-pytest%$COMPILER

Spack Build rhel7-ppc64le:
  stage: build rhel7-ppc64le
  variables:
    HOST : "lassen"
    SPACK_ENV_NAME : "rhel7-ppc64le"
    COMPILER : "gcc@9.4.0"
  tags:
    - $HOST
    - shell
  script: *build_script

Spack Build rhel7-cascadelake:
  stage: build rhel7-cascadelake
  variables:
    HOST : "ruby"
    SPACK_ENV_NAME : "rhel7-cascadelake"
    COMPILER : "gcc@8.2.0"
  tags:
    - $HOST
    - shell
  script: *build_script

Spack Test:
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -t 30"
  stage: test
  before_script:
    - whoami
  parallel:
    matrix:
      - HOST : ["quartz"]
        SPACK_ENV_NAME : ["rhel7-broadwell"]
      - HOST : ["lassen"]
        SPACK_ENV_NAME : ["rhel7-ppc64le"]
      - HOST : ["ruby"]
        SPACK_ENV_NAME : ["rhel7-cascadelake"]
  tags:
    - batch
    - $HOST
  script:
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - spack env activate $SPACK_ENV_NAME
    - spack load exaworks py-pytest
    - export RADICAL_PILOT_DBURL=${MONGODB_CONNECTION_STRING}?tlsAllowInvalidCertificates=true
    - export run_id=$RANDOM
    - export branch=$CI_COMMIT_BRANCH
    - export url=$TESTING_HOST
    - export test="Spack"
    - export location="llnl-$HOST"
    - export contact="morton30@llnl.gov"
    - export imnumber="LLNL-MI-834241"
    - python3 ci/tests/test.py -s
    - >
        for TEST in flux parsl rp swift-t parsl-flux; do
        python3 ci/tests/test.py -n $TEST -c
        "bash ci/tests/${TEST}/test.sh";
        done;
    - python3 ci/tests/test.py -e
  after_script:
    - whoami
