stages:
  - setup
  - compile
  - update
  - build
  - test
  - cleanup

.final_steps:
  script: &finalize
    - chgrp -fR exaworks $SPACK_WORK_DIR/spack || true
    - chmod -fR 02770 $SPACK_WORK_DIR/spack    || true

spack-setup:
  stage: setup
  tags:
    - quartz
    - shell
  script:
    - mkdir -p $SPACK_WORK_DIR
    - test -d $SPACK_WORK_DIR/spack && exit 0
    - git clone -c feature.manyFiles=true -c core.sharedRepository=true https://github.com/spack/spack.git $SPACK_WORK_DIR/spack
    - *finalize

env-setup:
  stage: compile
  needs:
    - job: spack-setup
  parallel:
    matrix:
      - HOST: [ "quartz" ]
        SPACK_ENV_NAME: [ "rhel7-broadwell" ]
        COMPILER: [ "gcc@8.1.0" ]
        TARGET_ARCH_OPT: [ "target=x86_64" ]
      - HOST: [ "lassen" ]
        SPACK_ENV_NAME: [ "rhel7-ppc64le" ]
        COMPILER: [ "gcc@9.4.0" ]
        TARGET_ARCH_OPT: [ "target=ppc64le" ]
      - HOST: [ "ruby" ]
        SPACK_ENV_NAME: [ "rhel7-cascadelake" ]
        COMPILER: [ "gcc@8.2.0" ]
        TARGET_ARCH_OPT: [ "" ]
  tags:
    - $HOST
    - shell
  script:
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - test "$(spack env list | grep $SPACK_ENV_NAME)" && exit 0
    - spack env create $SPACK_ENV_NAME
    - for i in {1..3}; do 
        spack env activate $SPACK_ENV_NAME && break || sleep 5; 
      done
    - spack config add concretizer:unify:true
    - spack config add concretizer:reuse:false
    - spack config add config:db_lock_timeout:300
    - spack compiler find
    - spack add $COMPILER %gcc@4.9.3 $TARGET_ARCH_OPT
    - spack install || (spack env deactivate && spack env remove $SPACK_ENV_NAME -y && exit 1)
    - spack compiler add $(spack location -i $COMPILER)
    - *finalize

spack-update:
  stage: update
  tags:
    - quartz
    - shell
  script:
    - cd $SPACK_WORK_DIR/spack/
    - git checkout HEAD^ .
    - git reset --hard HEAD
    - git pull --ff
    - *finalize

spack-build:
  stage: build
  needs:
    - job: spack-update
  parallel:
    matrix:
      - HOST: [ "quartz" ]
        SPACK_ENV_NAME: [ "rhel7-broadwell" ]
        COMPILER: [ "gcc@8.1.0" ]
      - HOST: [ "lassen" ]
        SPACK_ENV_NAME: [ "rhel7-ppc64le" ]
        COMPILER: [ "gcc@9.4.0" ]
      - HOST: [ "ruby" ]
        SPACK_ENV_NAME: [ "rhel7-cascadelake" ]
        COMPILER: [ "gcc@8.2.0" ]
  tags:
    - $HOST
    - shell
  script:
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - for i in {1..3}; do
        spack env activate $SPACK_ENV_NAME && break || sleep 5;
      done
    - spack uninstall -y exaworks%$COMPILER py-pytest%$COMPILER || true
    - spack add exaworks%$COMPILER ^python@3.9 py-pytest%$COMPILER
    - spack concretize -f
    - spack install
    - *finalize

sdk-test:
  stage: test
  needs:
    - job: spack-build
  before_script:
    - whoami
  parallel:
    matrix:
      - HOST: [ "quartz" ]
        SPACK_ENV_NAME: [ "rhel7-broadwell" ]
        LLNL_SLURM_SCHEDULER_PARAMETERS: [ "--nodes=1 -t 30" ]
      - HOST: [ "lassen" ]
        SPACK_ENV_NAME: [ "rhel7-ppc64le" ]
        LLNL_LSF_SCHEDULER_PARAMETERS: [ "-nnodes 1 -W 30" ]
        LSB_JOB_STARTER: [ "ENVIRONMENT=BATCH /usr/tcetmp/bin/bsub_job_starter %USRCMD" ]
        ENVIRONMENT: [ "BATCH" ]
      - HOST: [ "ruby" ]
        SPACK_ENV_NAME: [ "rhel7-cascadelake" ]
        LLNL_SLURM_SCHEDULER_PARAMETERS: [ "--nodes=1 -t 30" ]
  tags:
    - $HOST
    - batch
  script:
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - for i in {1..3}; do
        spack env activate $SPACK_ENV_NAME && break || sleep 5;
      done
    - spack load exaworks py-pytest
    - export RADICAL_PILOT_DBURL=${MONGODB_CONNECTION_STRING}?tlsAllowInvalidCertificates=true
    - export run_id=$RANDOM
    - export branch=$CI_COMMIT_BRANCH
    - export url=$TESTING_HOST
    - export test="Spack"
    - export location="llnl-$HOST"
    - export contact="morton30@llnl.gov"
    - export imnumber="LLNL-MI-834241"
    - python3 ci/tests/test.py -s
    - for TEST in flux parsl rp swift-t parsl-flux rp-flux; do
        python3 ci/tests/test.py -n $TEST -c "bash ci/tests/${TEST}/test.sh";
      done
    - python3 ci/tests/test.py -e
  after_script:
    - whoami

.spack-cleanup: &spack-cleanup
  stage: cleanup
  tags:
    - quartz
    - shell
  script:
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - spack clean -a || true
    - rm -rf $HOME/.spack/cache
    - spack providers
    - *finalize

cleanup-on-compile-failure:
  needs: [ "env-setup" ]
  when: on_failure
  <<: *spack-cleanup

cleanup-on-build-failure:
  needs: [ "spack-build" ]
  when: on_failure
  <<: *spack-cleanup

cleanup-on-success:
  when: on_success
  <<: *spack-cleanup

