stages:
  - setup
  - test
  - cleanup

.final_steps:
  script: &finalize
    - chgrp -fR exaworks $SDK_WORK_DIR/pip || true
    - chmod -fR 02770 $SDK_WORK_DIR/pip    || true

pip-env-setup:
  stage: setup
  parallel:
    matrix:
      - HOST : [ "quartz" ]
        VENV_ENV_NAME: [ "quartz-env" ]
        RUNNER_TYPE: "shell"
      - HOST : [ "ruby" ]
        VENV_ENV_NAME: [ "ruby-env" ]
        RUNNER_TYPE: "shell"
      # - HOST : [ "lassen" ]
      #   ENVIRONMENT: [ "BATCH" ]
      #   VENV_ENV_NAME: [ "lassen-env" ]
      #   RUNNER_TYPE: "batch"
  tags:
    - $HOST
    - $RUNNER_TYPE
  script:
    - export REQUIREMENTS_DIR=$(pwd)
    - mkdir -p ${SDK_WORK_DIR}/pip/
    - cd ${SDK_WORK_DIR}/pip/
    - python3 -m venv ${VENV_ENV_NAME}
    - cd ${VENV_ENV_NAME}
    - source bin/activate
    - echo $REQUIREMENTS_DIR
    - ls $REQUIREMENTS_DIR
    - pip install --upgrade pip
    - pip install --no-cache-dir -r $REQUIREMENTS_DIR/venv-requirements.txt
    - pip list 
    - *finalize

pip-tests:
  stage: test
  needs: [ "pip-env-setup" ]
  parallel:
    matrix:
      - HOST : [ "quartz" ]
        VENV_ENV_NAME: [ "quartz-env" ]
        RUNNER_TYPE: "shell"
      - HOST : [ "ruby" ]
        VENV_ENV_NAME: [ "ruby-env" ]
        RUNNER_TYPE: "shell"
      # - HOST : [ "lassen" ]
      #   ENVIRONMENT: [ "BATCH" ]
      #   VENV_ENV_NAME: [ "lassen-env" ]
      #   RUNNER_TYPE: "batch"
  tags:
    - $HOST
    - $RUNNER_TYPE
  script:
    - cd ${SDK_WORK_DIR}/pip/${VENV_ENV_NAME}
    - source ./bin/activate
    - cd SDK
    - export RADICAL_PILOT_DBURL=${MONGODB_CONNECTION_STRING}?tlsAllowInvalidCertificates=true
    - export run_id=$CI_PIPELINE_ID
    - export branch=$CI_COMMIT_BRANCH
    - export url=$TESTING_HOST
    - export test="Pip"
    - export location="llnl-$HOST"
    - export contact="arambula2@llnl.gov"
    - export imnumber="LLNL-MI-834241"
    - python3 ci/tests/test.py -s
    - for TEST in flux parsl rp swift-t parsl-flux rp-flux; do
        python3 ci/tests/test.py -n $TEST -c "bash ci/tests/${TEST}/test.sh";
      done
    - python3 ci/tests/test.py -e
    - deactivate

.pip-env-cleanup: &pip-env-cleanup
  stage: cleanup
  tags:
    - quartz
    - shell
  script:
    - cd $SDK_WORK_DIR
    - rm -rf pip
    - *finalize

pip-cleanup-on-env-setup-failure:
  needs: [ "pip-env-setup" ]
  when: on_failure
  <<: *pip-env-cleanup

pip-cleanup-on-test-failure:
  needs: [ "pip-tests" ]
  when: on_failure
  <<: *pip-env-cleanup

pip-cleanup-on-success:
  needs: [ "pip-tests" ]
  when: on_success
  <<: *pip-env-cleanup
