stages:
  - update
  - build
  - test

default:
  after_script:
    - cd $SPACK_WORK_DIR/spack/
    - chgrp -fR exaworks . && chmod -fR 02770 .

spack-update:
  stage: update
  tags:
    - quartz
    - shell
  script:
    - cd $SPACK_WORK_DIR/spack/
    - git checkout HEAD^ .
    - git reset --hard HEAD
    - git pull --ff

spack-build-quartz:
  stage: build
  needs:
    - job: spack-update
  variables:
    HOST : "quartz"
    SPACK_ENV_NAME : "rhel7-broadwell"
    COMPILER : "gcc@8.1.0"
  tags:
    - $HOST
    - shell
  script: &build_script
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - spack env activate $SPACK_ENV_NAME
    - spack uninstall -y exaworks%$COMPILER  || true
    - spack uninstall -y py-pytest%$COMPILER || true
    - spack install --fresh exaworks%$COMPILER py-pytest%$COMPILER

spack-build-lassen:
  stage: build
  needs:
    - job: spack-update
  variables:
    HOST : "lassen"
    SPACK_ENV_NAME : "rhel7-ppc64le"
    COMPILER : "gcc@9.4.0"
  tags:
    - $HOST
    - shell
  script: *build_script

spack-build-ruby:
  stage: build
  needs:
    - job: spack-update
  variables:
    HOST : "ruby"
    SPACK_ENV_NAME : "rhel7-cascadelake"
    COMPILER : "gcc@8.2.0"
  tags:
    - $HOST
    - shell
  script: *build_script

sdk-test:
  stage: test
  needs:
    - job: spack-build-quartz
    - job: spack-build-lassen
    - job: spack-build-ruby
  variables:
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -t 30"
  before_script:
    - whoami
  parallel:
    matrix:
      - HOST : ["quartz"]
        SPACK_ENV_NAME : ["rhel7-broadwell"]
      - HOST : ["lassen"]
        SPACK_ENV_NAME : ["rhel7-ppc64le"]
      - HOST : ["ruby"]
        SPACK_ENV_NAME : ["rhel7-cascadelake"]
  tags:
    - batch
    - $HOST
  script:
    - . $SPACK_WORK_DIR/spack/share/spack/setup-env.sh
    - spack env activate $SPACK_ENV_NAME
    - spack load exaworks py-pytest
    - export RADICAL_PILOT_DBURL=${MONGODB_CONNECTION_STRING}?tlsAllowInvalidCertificates=true
    - export run_id=$RANDOM
    - export branch=$CI_COMMIT_BRANCH
    - export url=$TESTING_HOST
    - export test="Spack"
    - export location="llnl-$HOST"
    - export contact="morton30@llnl.gov"
    - export imnumber="LLNL-MI-834241"
    - python3 ci/tests/test.py -s
    - >
        for TEST in flux parsl rp swift-t parsl-flux; do
            python3 ci/tests/test.py -n $TEST -c
            "bash ci/tests/${TEST}/test.sh";
        done;
    - python3 ci/tests/test.py -e
  after_script:
    - whoami

