variables:
  PIP_WORK_DIR: ${SDK_WORK_DIR}/pip
  PIP_REQUIREMENTS: .gitlab/venv-requirements.txt
  RADICAL_PILOT_DBURL: ${MONGODB_CONNECTION_STRING}?tlsAllowInvalidCertificates=true

stages:
  - setup
  - build
  - test
  - cleanup

.job_tags:
  tags:
    - $HOST
    - $RUNNER_TYPE

.final_steps:
  script: &finalize
    - chgrp -fR exaworks ${PIP_WORK_DIR} || true
    - chmod -fR 02770 ${PIP_WORK_DIR}    || true

.on_quartz:
  variables:
    HOST: "quartz"
    VENV_ENV_NAME: "quartz-env"

# .on_ruby:
#   HOST : "ruby"
#   VENV_ENV_NAME: "ruby-env"

.pip-env-setup:
  stage: setup
  script:
    - mkdir -p ${PIP_WORK_DIR}
    - test -d ${PIP_WORK_DIR}/${VENV_ENV_NAME} && exit 0
    - python3 -m venv ${PIP_WORK_DIR}/${VENV_ENV_NAME}
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install -U pip setuptools wheel
    - pip cache purge

.pip-build:
  stage: build
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install --no-cache-dir -r ${PIP_REQUIREMENTS}
    - *finalize

.pip-test:
  stage: test
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - export run_id=${CI_PIPELINE_ID}
    - export branch=${CI_COMMIT_BRANCH}
    - export url=${TESTING_HOST}
    - export test="Pip"
    - export location="llnl-$HOST"
    - export contact="arambula2@llnl.gov"
    - export imnumber="LLNL-MI-834241"
    - python3 ci/tests/test.py -s
    - for TEST in flux parsl rp swift-t parsl-flux rp-flux maestro; do
        python3 ci/tests/test.py -n $TEST -c "bash ci/tests/${TEST}/test.sh";
      done
    - python3 ci/tests/test.py -e
    - deactivate

.pip-env-cleanup:
  stage: cleanup
  script:
    - source ${PIP_WORK_DIR}/ruby-env/bin/activate
    - pip cache purge
    - *finalize



setup_on_quartz:
  variables:
    RUNNER_TYPE: "shell"
  extends: [.on_quartz, .job_tags, .pip_env_setup]

build_on_quartz:
  variables:
    RUNNER_TYPE: "shell"
  needs: [setup_on_quartz]
  extends: [.on_quartz, .job_tags, .pip_build]

test_on_quartz:
  variables:
    RUNNER_TYPE: "batch"
    LLNL_SLURM_SCHEDULER_PARAMETERS: "--nodes=1 -t 30"
  needs: [build_on_quartz]
  extends: [.on_quartz, .job_tags, .pip_test]

cleanup_on_quartz:
  variables:
    RUNNER_TYPE: "shell"
  needs: [test_on_quartz]
  when: always
  extends: [.on_quartz, .job_tags, .pip_env_cleanup]

# setup_on_ruby:
#   RUNNER_TYPE: "shell"
#   extends: [.on_ruby, .pip-env-setup]

# pip-env-setup:
#   stage: setup
#   parallel:
#     matrix:
#       - HOST : [ "quartz" ]
#         VENV_ENV_NAME: [ "quartz-env" ]
#         RUNNER_TYPE: "shell"
#       - HOST : [ "ruby" ]
#         VENV_ENV_NAME: [ "ruby-env" ]
#         RUNNER_TYPE: "shell"
#       # - HOST : [ "lassen" ]
#       #   ENVIRONMENT: [ "BATCH" ]
#       #   VENV_ENV_NAME: [ "lassen-env" ]
#       #   RUNNER_TYPE: "batch"
#   tags:
#     - $HOST
#     - $RUNNER_TYPE
#   script:
#     - mkdir -p ${PIP_WORK_DIR}
#     - test -d ${PIP_WORK_DIR}/${VENV_ENV_NAME} && exit 0
#     - python3 -m venv ${PIP_WORK_DIR}/${VENV_ENV_NAME}
#     - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
#     - pip install -U pip setuptools wheel
#     - pip cache purge



# build_on_ruby:
#   HOST : [ "ruby" ]
#   VENV_ENV_NAME: [ "ruby-env" ]
#   RUNNER_TYPE: "shell"
#   needs: [setup-on_ruby]
#   extends: [.pip-build]


# pip-build:
#   stage: build
#   needs:
#     - job: pip-env-setup
#   parallel:
#     matrix:
#       - HOST : [ "quartz" ]
#         VENV_ENV_NAME: [ "quartz-env" ]
#         RUNNER_TYPE: "shell"
#       - HOST : [ "ruby" ]
#         VENV_ENV_NAME: [ "ruby-env" ]
#         RUNNER_TYPE: "shell"
#       # - HOST : [ "lassen" ]
#       #   ENVIRONMENT: [ "BATCH" ]
#       #   VENV_ENV_NAME: [ "lassen-env" ]
#       #   RUNNER_TYPE: "batch"
#   tags:
#     - $HOST
#     - $RUNNER_TYPE
#   script:
#     - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
#     - pip install --no-cache-dir -r ${PIP_REQUIREMENTS}
#     - *finalize



# test_on_ruby:
#   HOST : [ "ruby" ]
#   VENV_ENV_NAME: [ "ruby-env" ]
#   RUNNER_TYPE: "batch"
#   LLNL_SLURM_SCHEDULER_PARAMETERS: [ "--nodes=1 -t 30" ]
#   needs: [build_on_ruby]
#   extends: [pip-test]

# pip-tests:
#   stage: test
#   needs: 
#     - job: pip-build
#   parallel:
#     matrix:
#       - HOST : [ "quartz" ]
#         VENV_ENV_NAME: [ "quartz-env" ]
#         RUNNER_TYPE: "batch"
#         LLNL_SLURM_SCHEDULER_PARAMETERS: [ "--nodes=1 -t 30" ]
#       - HOST : [ "ruby" ]
#         VENV_ENV_NAME: [ "ruby-env" ]
#         RUNNER_TYPE: "batch"
#         LLNL_SLURM_SCHEDULER_PARAMETERS: [ "--nodes=1 -t 30" ]
#       # - HOST : [ "lassen" ]
#       #   ENVIRONMENT: [ "BATCH" ]
#       #   VENV_ENV_NAME: [ "lassen-env" ]
#       #   RUNNER_TYPE: "batch"
#         # LLNL_LSF_SCHEDULER_PARAMETERS: [ "-nnodes 1 -W 30" ]
#         # LSB_JOB_STARTER: [ "ENVIRONMENT=BATCH /usr/tcetmp/bin/bsub_job_starter %USRCMD" ]
#   tags:
#     - $HOST
#     - $RUNNER_TYPE
#   script:
#     - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
#     - export run_id=${CI_PIPELINE_ID}
#     - export branch=${CI_COMMIT_BRANCH}
#     - export url=${TESTING_HOST}
#     - export test="Pip"
#     - export location="llnl-$HOST"
#     - export contact="arambula2@llnl.gov"
#     - export imnumber="LLNL-MI-834241"
#     - python3 ci/tests/test.py -s
#     - for TEST in flux parsl rp swift-t parsl-flux rp-flux maestro; do
#         python3 ci/tests/test.py -n $TEST -c "bash ci/tests/${TEST}/test.sh";
#       done
#     - python3 ci/tests/test.py -e
#     - deactivate

# pip-cleanup-on-build-failure:
#   needs:
#     - job: pip-build
#   when: on_failure
#   <<: *pip-env-cleanup

# pip-cleanup-on-test-failure:
#   needs:
#     - job: pip-tests
#   when: on_failure
#   <<: *pip-env-cleanup

# pip-cleanup-on-success:
#   needs:
#     - job: pip-tests
#   when: on_success
#   <<: *pip-env-cleanup



