variables:
  PIP_WORK_DIR: ${SDK_WORK_DIR}/pip
  PIP_REQUIREMENTS: .gitlab/pip-requirements.txt
  SITE: "perlmutter"
  VENV_ENV_NAME: "perlmutter-env"
# python/3.10 works too, python/3.11 breaks on 'pip install --no-cache-dir -r ${PIP_REQUIREMENTS}' in .pip_build; fails to satisfy requirement smartsim==0.5.1
  PYTHON_MODULE: "python/3.9"
  MAINTAINER: "cowan@bnl.gov"
  IM_NUMBER: ""
  TESTS_GROUP: "pip"
  SITE_ID: "nersc-$SITE"


stages:
  - setup
  - build
  - test
  - cleanup


### MACHINES
#.on_perlmutter: &on_perlmutter_tmpl
#  variables:

### SCRIPTS
.job_tags: &job_tags_tmpl
  tags:
    - $SITE
    - $RUNNER_TYPE

.pip_env_setup: &pip_env_setup_tmpl
  stage: setup
  script:
    - mkdir -p ${PIP_WORK_DIR}
    - test -d ${PIP_WORK_DIR}/${VENV_ENV_NAME} && exit 0
    - module add ${PYTHON_MODULE}
    - python3 -m venv ${PIP_WORK_DIR}/${VENV_ENV_NAME}
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install --upgrade pip
    - pip install -U pip setuptools wheel
    - pip cache purge
#    - chgrp -fR m3973 ${PIP_WORK_DIR} || true
#    - chmod -fR 02770 ${PIP_WORK_DIR} || true

.pip_build: &pip_build_tmpl
  stage: build
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install --no-cache-dir -r ${PIP_REQUIREMENTS}
    - (smart clean && smart build) > /dev/null 2>&1 || true
#    - chgrp -fR m3973 ${PIP_WORK_DIR} || true
#    - chmod -fR 02770 ${PIP_WORK_DIR} || true


.pip_test: &pip_test_tmpl
  stage: test
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - python3 ci/tests/test.py -s
    - for TEST in parsl rp maestro smartsim; do
        python3 ci/tests/test.py -n $TEST -c "bash ci/tests/${TEST}/test.sh" --stdout;
      done
    - python3 ci/tests/test.py -e
    - deactivate
#    - chgrp -fR m3973 ${PIP_WORK_DIR} || true
#    - chmod -fR 02770 ${PIP_WORK_DIR} || true


### JOBS

# PERLMUTTER
pip_env_setup_perlmutter:
  variables:
    RUNNER_TYPE: "shell"
#  <<: *on_perlmutter_tmpl
  <<: *job_tags_tmpl
  <<: *pip_env_setup_tmpl

pip_build_perlmutter:
  variables:
    RUNNER_TYPE: "shell"
  needs: [ pip_env_setup_perlmutter ]
#  <<: *on_perlmutter_tmpl
  <<: *job_tags_tmpl
  <<: *pip_build_tmpl

pip_test_perlmutter:
  variables:
    RUNNER_TYPE: "batch"
    SCHEDULER_PARAMETERS: "--nodes=1 -t 45"
  needs: [ pip_build_perlmutter ]
#  <<: *on_perlmutter_tmpl
  <<: *job_tags_tmpl
  <<: *pip_test_tmpl


# ALWAYS
pip_cleanup:
  stage: cleanup
  when: always
  variables:
    RUNNER_TYPE: "shell"
#  <<: *on_perlmutter_tmpl
  <<: *job_tags_tmpl
  script:
    - time chgrp -fR m3973 ${PIP_WORK_DIR} || true
    - time chmod -fR 02770 ${PIP_WORK_DIR} || true
