variables:
  PIP_WORK_DIR: ${SDK_WORK_DIR_ALPINE}/pip
  PIP_REQUIREMENTS: .gitlab/pip-requirements.txt


stages:
  - setup
  - build
  - test
  - cleanup


### MACHINES
.on_summit:
  variables:
    SITE: "summit"
    VENV_ENV_NAME: "summit-env"


### SCRIPTS
.final_steps:
  script: &finalize
    - chgrp -fR csc449 ${PIP_WORK_DIR} || true
    - chmod -fR 02770 ${PIP_WORK_DIR}    || true

.job_tags:
  tags:
    - $SITE
    - $RUNNER_TYPE

.pip_env_setup:
  stage: setup
  script:
    - mkdir -p ${PIP_WORK_DIR}
    - test -d ${PIP_WORK_DIR}/${VENV_ENV_NAME} && exit 0
    - python3 -m venv ${PIP_WORK_DIR}/${VENV_ENV_NAME}
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install -U pip setuptools wheel
    - pip cache purge
    - *finalize

.pip_build:
  stage: build
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - pip install --no-cache-dir -r ${PIP_REQUIREMENTS}
    - *finalize

.pip_test:
  stage: test
  variables:
    MAINTAINER: "arambula2@llnl.gov"
    TESTS_GROUP: "pip"
    SITE_ID: "ornl-$SITE"
  script:
    - source ${PIP_WORK_DIR}/${VENV_ENV_NAME}/bin/activate
    - python3 ci/tests/test.py -s
    - for TEST in flux parsl rp parsl-flux rp-flux maestro; do
        python3 ci/tests/test.py -n $TEST -c "bash ci/tests/${TEST}/test.sh" --stdout;
      done
    - python3 ci/tests/test.py -e
    - deactivate

### JOBS

# SUMMIT
pip_env_setup_summit:
  variables:
    RUNNER_TYPE: "nobatch"
  extends: [ .on_summit, .job_tags, .pip_env_setup ]

pip_build_summit:
  variables:
    RUNNER_TYPE: "nobatch"
  needs: [ pip_env_setup_summit ]
  extends: [ .on_summit, .job_tags, .pip_build ]

pip_test_summit:
  variables:
    RUNNER_TYPE: "batch"
    SCHEDULER_PARAMETERS: "-P CSC449 -nnodes 1 -W 45"
  needs: [ pip_build_summit ]
  extends: [ .on_summit, .job_tags, .pip_test ]


# ALWAYS
pip_cleanup:
  stage: cleanup
  when: always
  variables:
    RUNNER_TYPE: "nobatch"
  extends: [ .on_summit, .job_tags ]
  script:
   - *finalize
