
stages:
  - build
  - test
  - clean

Spack Build:
  stage: build
  tags:
    - nobatch
  needs: []
  variables:
#    CUSTOM_CI_BUILDS_DIR: "/gpfs/wolf/proj-shared/csc449/ci/${CI_PIPELINE_ID}"
    WORK: "/gpfs/wolf/proj-shared/csc449/ci/"
  script:
    - pwd
    - env | grep CI_
    - export run_id=$CI_PIPELINE_ID
    - export branch=$CI_COMMIT_BRANCH
    - export url="https://sdk.testing.exaworks.org/result"
    - export test="Spack"
    - export location="ornl-$(echo $CI_RUNNER_TAGS | cut -f 1 -d ',')"
    - export contact="andre@merzky.net"
    - python3 ci/tests/test.py -s
    - test -d $WORK/spack || git clone -c feature.manyFiles=true https://github.com/spack/spack.git $WORK/spack
    - pushd $WORK/spack/
    - git checkout HEAD^ .
    - git pull --ff
    - popd
    - chmod -fR 02770 . || true
    - . $WORK/spack/share/spack/setup-env.sh
    - spack install py-pytest
    - python3 ci/tests/test.py -n 'spack build' -c "spack install exaworks"


Spack Test:
  stage: test
  parallel:
      matrix:
        - TEST : ["rp", "swift-t", "parsl", "flux", "rp-flux", "parsl-flux"]
  tags:
    - batch
  needs: [Spack Build]
  variables:
    SCHEDULER_PARAMETERS: "-P CSC449 -nnodes 1 -W 30"
#    CUSTOM_CI_BUILDS_DIR: "/gpfs/wolf/proj-shared/csc449/ci/${CI_PIPELINE_ID}"
    WORK: "/gpfs/wolf/proj-shared/csc449/ci/"
  script:
    - . $WORK/spack/share/spack/setup-env.sh
    - spack env activate $SPACK_ENV_NAME
    - spack uninstall -y exaworks%$COMPILER  || true
    - spack uninstall -y py-pytest%$COMPILER || true
    - spack install --fresh exaworks%$COMPILER py-pytest%$COMPILER
    - spack load exaworks py-pytest
    - export run_id=$CI_PIPELINE_ID
    - export branch=$CI_COMMIT_BRANCH
    - export url="https://sdk.testing.exaworks.org/result"
    - export test="$TEST"
    - export location="ornl-$(echo $CI_RUNNER_TAGS | cut -f 1 -d ',')"
    - export contact="andre@merzky.net"
    - python3 ci/tests/test.py --stdout -n "$TEST" -c "bash ci/tests/${TEST}/test.sh"


Spack Clean:
  stage: clean
  tags:
    - nobatch
  needs: [Spack Test]
  variables:
    WORK: "/gpfs/wolf/proj-shared/csc449/ci/"
  script:
    - export run_id=$CI_PIPELINE_ID
    - export branch=$CI_COMMIT_BRANCH
    - export url="https://sdk.testing.exaworks.org/result"
    - export test="upload"
    - export location="ornl-$(echo $CI_RUNNER_TAGS | cut -f 1 -d ',')"
    - export contact="andre@merzky.net"
#    - export imnumber="LLNL-MI-834241"
    - python3 ci/tests/test.py -e
#    - rm -rf $WORK/spack/

