channels:
  - conda-forge
dependencies:
  - autoconf
  - automake
  - boost
  - boost-cpp
  - "cffi>=1.1"
  - cryptography=3.3.2
  - "czmq>=3.0.1"
  - jansson=2.11
  - jsonschema=2
  - jq
  - libedit
  - libhwloc=1.11
  - libtool
  - libuuid
  - libxml2
  - lua=5.4
  - lua-luaposix
  - lz4
  - make
  - mongodb
  - mpi
  - munge
  - openjdk=8
  - pip
  - pkgconfig
  - pytest
  - python=3.6
  - python_abi
  - "pyyaml>=3.10.0"
  - setuptools
  - six
  - "sqlite>=3.0.0"
  - swig
  - tk=8.6
  - valgrind
  - yaml-cpp
  - yaml-cpp-static
  - "zeromq>=4.0.4"
  - zlib
  - zsh
  - zstd

#  - mpich
#  - openmpi=4.0
