name: CI Test RP
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Build docker images
      run: |
        docker build -t base docker/base
        docker build -t rp   docker/rp

    - name: Run tests
      run: |
        docker run rp

