name: Deploy
on:
  push: { branches: master }

jobs:
  test:
    name: Deploy docker images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dockerbase: ["centos7", "rockylinux8", "ubuntu2004"]
        packagemanager: [ "pip", "conda" ]
        mpi: ["openmpi", "mpich"]
        exclude:
          - dockerbase: "centos7"
            packagemanager: "conda"
    env:
      DOCKER_TAG: "${{ matrix.dockerbase }}_${{ matrix.packagemanager }}_${{ matrix.mpi }}"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push base image (${{ env.DOCKER_TAG }})
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./docker/base/
        file: ./docker/base/${{ matrix.dockerbase }}/Dockerfile
        push: true
        build-args: |
          PACKAGE_MANAGER=${{ matrix.packagemanager }}
          MPI=${{ matrix.mpi }}
        tags: |
          exaworks/sdk-base:${{ env.DOCKER_TAG }}
        platforms: linux/amd64

    - name: Build and push composite image (${{ env.DOCKER_TAG }})
      run: |
        docker build \
          -t rp:${{ env.DOCKER_TAG }} \
          --build-arg BASE_IMAGE=exaworks/sdk-base:${{ env.DOCKER_TAG }} \
          docker/rp
        docker build \
          -t rp_parsl:${{ env.DOCKER_TAG }} \
          --build-arg BASE_IMAGE=rp:${{ env.DOCKER_TAG }} \
          docker/parsl
        docker build \
          -t rp_parsl_swift:${{ env.DOCKER_TAG }} \
          --build-arg BASE_IMAGE=rp_parsl:${{ env.DOCKER_TAG }} \
          docker/swift-t
        docker build \
          -t exaworks/sdk:${{ env.DOCKER_TAG }} \
          --build-arg BASE_IMAGE=rp_parsl_swift:${{ env.DOCKER_TAG }} \
          docker/flux
        docker push exaworks/sdk:${{ env.DOCKER_TAG }}

    - name: Push images with 'latest' tag
      if: ${{ matrix.dockerbase == 'centos7' \
              && matrix.packagemanager == 'pip' \
              && matrix.mpi == 'openmpi' }}
      run: |
        docker tag exaworks/sdk-base:${{ env.DOCKER_TAG }} exaworks/sdk-base:latest
        docker push exaworks/sdk-base:latest
        docker tag exaworks/sdk:${{ env.DOCKER_TAG }} exaworks/sdk:latest
        docker push exaworks/sdk:latest
