name: Deploy
on:
  push: { branches: master }

jobs:
  test:
    name: Deploy docker images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dockerbase: ["centos7", "centos8", "ubuntu2004"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push base image (${{ matrix.dockerbase }})
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./docker/base/
        file: ./docker/base/${{ matrix.dockerbase }}/Dockerfile
        push: true
        tags: |
          exaworks/sdk-base:${{ matrix.dockerbase }}
        platforms: linux/amd64

    - name: Build and push composite image (${{ matrix.dockerbase }})
      run: |
        docker build \
          -t rp:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=exaworks/sdk-base:${{ matrix.dockerbase }} \
          docker/rp
        docker build \
          -t rp_parsl:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=rp:${{ matrix.dockerbase }} \
          docker/Parsl
        docker build \
          -t rp_parsl_swift:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=rp_parsl:${{ matrix.dockerbase }} \
          docker/swift-t
        docker build \
          -t exaworks/sdk:${{ matrix.dockerbase }} \
          --build-arg BASE_IMAGE=rp_parsl_swift:${{ matrix.dockerbase }} \
          docker/flux
        docker push exaworks/sdk:${{ matrix.dockerbase }}

    - name: Push images with 'latest' tag
      if: ${{ matrix.dockerbase == 'centos7' }}
      run: |
        docker tag exaworks/sdk-base:${{ matrix.dockerbase }} exaworks/sdk-base:latest
        docker push exaworks/sdk-base:latest
        docker tag exaworks/sdk:${{ matrix.dockerbase }} exaworks/sdk:latest
        docker push exaworks/sdk:latest
